on:
  # ruleid: ratchet-gha-untrusted-checkout-with-secrets
  pull_request_target:

jobs:
  build:
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
